language: scala
scala:
   - 2.11.12
   - 2.12.10
   - 2.13.1
os: 
  - osx
  - linux
osx_image: xcode9.3
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8

script:
  - "cd core"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publishLocal"
  - "cd .."
  - "cd simulator"
  - "sbt ++$TRAVIS_SCALA_VERSION test"

matrix:
  exclude:
    - os: osx
      jdk: openjdk8
    - os: osx
      jdk: oraclejdk9
    - os: osx
      jdk: oraclejdk11

  allow_failures:
    - jdk: oraclejdk9
    - jdk: oraclejdk11
